$$
q(w_{ij})=N(w_{ij}|\mu_{ij}, \mu_{ij}^2\sigma_{ij}^2) \\
a_{ij} = \sum_{i} x_i w_{ij} \\
q(a_{ij}) = 
$$

In [3]:
import torch
import torch.nn as nn

In [11]:
a = nn.Linear(1,1)

In [12]:
b = a.weight

In [13]:
b.grad

In [14]:
a(torch.randn(1)).backward()

In [15]:
b.grad

tensor([[1.3283]])

In [20]:
a.weight = nn.Parameter(torch.empty(a.weight.shape).normal_())

In [21]:
b.grad

tensor([[1.3283]])

In [22]:
a(torch.randn(1)).backward()

In [23]:
b.grad

tensor([[1.3283]])

In [24]:
a.weight.grad

tensor([[0.6290]])

In [26]:
b.cuda()

tensor([[-0.5922]], device='cuda:0', grad_fn=<CopyBackwards>)

In [27]:
a = a.cuda()

In [31]:
a.weight

Parameter containing:
tensor([[0.2384]], device='cuda:0', requires_grad=True)

In [32]:
from utils import mul_sign